apiVersion: v1
kind: Secret
metadata:
  name: github-personal-token
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: "$HTTPS_URL"
  password: "$GITHUB_PERSONAL_TOKEN"
  username: not-used
