apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vault-token
  namespace: external-secrets
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    token: "$SEALED_TOKEN"
