apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: development-chanh
  namespace: development
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: development-chanh
  dataFrom:
    - extract:
        key: api-main
